[2023-11-27T12:58:00.799+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airbyte_example_airflow_dag.move_raw_products_file manual__2023-11-27T12:56:52.053901+00:00 [queued]>
[2023-11-27T12:58:00.806+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airbyte_example_airflow_dag.move_raw_products_file manual__2023-11-27T12:56:52.053901+00:00 [queued]>
[2023-11-27T12:58:00.806+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-27T12:58:00.837+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): move_raw_products_file> on 2023-11-27 12:56:52.053901+00:00
[2023-11-27T12:58:00.842+0000] {standard_task_runner.py:57} INFO - Started process 3084 to run task
[2023-11-27T12:58:00.844+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'airbyte_example_***_dag', 'move_raw_products_file', 'manual__2023-11-27T12:56:52.053901+00:00', '--job-id', '149', '--raw', '--subdir', 'DAGS_FOLDER/example.py', '--cfg-path', '/tmp/tmp_3a_e_7_']
[2023-11-27T12:58:00.845+0000] {standard_task_runner.py:85} INFO - Job 149: Subtask move_raw_products_file
[2023-11-27T12:58:00.921+0000] {task_command.py:416} INFO - Running <TaskInstance: airbyte_example_airflow_dag.move_raw_products_file manual__2023-11-27T12:56:52.053901+00:00 [running]> on host 471f0a6f2fee
[2023-11-27T12:58:01.049+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='airbyte_example_***_dag' AIRFLOW_CTX_TASK_ID='move_raw_products_file' AIRFLOW_CTX_EXECUTION_DATE='2023-11-27T12:56:52.053901+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-27T12:56:52.053901+00:00'
[2023-11-27T12:58:01.115+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-27T12:58:01.116+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'sudo mv /tmp/airbyte_local/json_from_faker/_airbyte_raw_products.jsonl /tmp/airbyte_local/json_from_faker/moved_raw_products.jsonl']
[2023-11-27T12:58:01.134+0000] {subprocess.py:86} INFO - Output:
[2023-11-27T12:58:01.143+0000] {subprocess.py:93} INFO - 
[2023-11-27T12:58:01.143+0000] {subprocess.py:93} INFO - We trust you have received the usual lecture from the local System
[2023-11-27T12:58:01.143+0000] {subprocess.py:93} INFO - Administrator. It usually boils down to these three things:
[2023-11-27T12:58:01.143+0000] {subprocess.py:93} INFO - 
[2023-11-27T12:58:01.144+0000] {subprocess.py:93} INFO -     #1) Respect the privacy of others.
[2023-11-27T12:58:01.144+0000] {subprocess.py:93} INFO -     #2) Think before you type.
[2023-11-27T12:58:01.144+0000] {subprocess.py:93} INFO -     #3) With great power comes great responsibility.
[2023-11-27T12:58:01.144+0000] {subprocess.py:93} INFO - 
[2023-11-27T12:58:01.144+0000] {subprocess.py:93} INFO - sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
[2023-11-27T12:58:01.144+0000] {subprocess.py:93} INFO - sudo: a password is required
[2023-11-27T12:58:01.145+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-11-27T12:58:01.154+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-11-27T12:58:01.156+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=airbyte_example_***_dag, task_id=move_raw_products_file, execution_date=20231127T125652, start_date=20231127T125800, end_date=20231127T125801
[2023-11-27T12:58:01.268+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 149 for task move_raw_products_file (Bash command failed. The command returned a non-zero exit code 1.; 3084)
[2023-11-27T12:58:01.297+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-27T12:58:01.325+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
